#! /bin/bash
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
curl -LO https://github.com/kubernetes/kops/releases/latest/download/kops-linux-amd64
chmod +x kubectl
sudo mv kubectl /usr/local/bin/
chmod +x kops-linux-amd64
sudo mv kops-linux-amd64 /usr/local/bin/kops


export KOPS_STATE_STORE=s3://suresh.devops
kops create cluster --name suresh.k8s.local --zones us-east-1a,us-east-1b --master-count=1 --master-size t2.medium --master-volume-size=30 --node-count=2 --node-size t2.micro --node-volume-size=20
kops update cluster --name suresh.k8s.local --yes --admin
